# Generated by Django 3.0 on 2019-12-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('emp_name', models.CharField(max_length=14)),
                ('emp_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('rank', models.CharField(max_length=10)),
                ('salary', models.CharField(max_length=8)),
                ('phone_number', models.CharField(max_length=14)),
                ('sex', models.CharField(max_length=1)),
                ('birthdate', models.CharField(max_length=10)),
                ('recruit_date', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=30)),
                ('photo', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=2)),
            ],
        ),
    ]
