# Generated by Django 3.0 on 2020-01-08 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f1app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dependent',
            fields=[
                ('dep_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dep_name', models.CharField(max_length=14)),
                ('dep_sex', models.CharField(max_length=1)),
                ('birthdate', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='rank',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('emp_name', 'emp_id')},
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('country_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=14)),
                ('continent_attr', models.CharField(max_length=14)),
                ('head_of_state', models.CharField(max_length=14)),
                ('foreign_minister', models.CharField(max_length=14)),
                ('liaison', models.CharField(max_length=14)),
                ('country_population', models.IntegerField()),
                ('country_area', models.IntegerField()),
                ('contact_number', models.CharField(max_length=14)),
                ('has_diplomatic_relatioin', models.CharField(max_length=6)),
                ('ambassador_name', models.CharField(max_length=14)),
                ('alive', models.CharField(max_length=2)),
            ],
            options={
                'unique_together': {('country_code', 'country_name')},
            },
        ),
        migrations.CreateModel(
            name='dependemp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('relation', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=2)),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1app.dependent')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1app.employee')),
            ],
            options={
                'unique_together': {('emp_id', 'dep_id')},
            },
        ),
        migrations.CreateModel(
            name='agent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('arrival_date', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=2)),
                ('country_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1app.country')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1app.employee')),
            ],
            options={
                'unique_together': {('emp_id', 'country_code')},
            },
        ),
    ]
