# Generated by Django 3.0 on 2020-01-09 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f1app', '0002_auto_20200109_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='alive',
            new_name='status',
        ),
    ]
